../../tb/dsport/xilinx_pcie_2_0_rport_v6.v
../../tb/dsport/pcie_2_0_rport_v6.v
../../tb/dsport/pci_exp_usrapp_com.v
../../tb/dsport/pci_exp_usrapp_tx.v
../../tb/dsport/pci_exp_usrapp_cfg.v
../../tb/dsport/pci_exp_usrapp_rx.v
../../tb/dsport/pci_exp_usrapp_pl.v


../../tb/source/pcie_gtx_v6.v
../../tb/source/gtx_drp_chanalign_fix_3752_v6.v
../../tb/source/gtx_wrapper_v6.v
../../tb/source/gtx_rx_valid_filter_v6.v
../../tb/source/gtx_tx_sync_rate_v6.v
../../tb/source/pcie_bram_top_v6.v
../../tb/source/pcie_brams_v6.v
../../tb/source/pcie_bram_v6.v
../../tb/source/pcie_clocking_v6.v
../../tb/source/pcie_pipe_v6.v
../../tb/source/pcie_pipe_lane_v6.v
../../tb/source/pcie_pipe_misc_v6.v
../../tb/source/pcie_reset_delay_v6.v
../../tb/source/axi_basic_tx_thrtl_ctl.v
../../tb/source/axi_basic_rx.v
../../tb/source/axi_basic_rx_null_gen.v
../../tb/source/axi_basic_rx_pipeline.v
../../tb/source/axi_basic_tx_pipeline.v
../../tb/source/axi_basic_tx.v
../../tb/source/axi_basic_top.v
../../tb/source/pcie_2_0_v6.v
../../tb/source/pcie_upconfig_fix_3451_v6.v
../../tb/source/v6_pcie_v2_5.v
